System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "components/*": "app/js/components/*",
    "configuration": "app/js/config.js",
    "tide/*": "app/js/tide/*"
  },
  bundles: {
    "dist/dev/mobx.js": [
      "npm:mobx-react@3.0.3.js",
      "npm:mobx-react@3.0.3/index.js",
      "npm:mobx@2.0.4.js",
      "npm:mobx@2.0.4/lib/mobx.js",
      "npm:react@0.14.8.js",
      "npm:react-dom@0.14.8.js",
      "npm:react@0.14.8/react.js",
      "npm:react-dom@0.14.8/index.js",
      "npm:react@0.14.8/lib/React.js",
      "npm:react@0.14.8/lib/ReactDOM.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js",
      "npm:react@0.14.8/lib/Object.assign.js",
      "npm:react@0.14.8/lib/ReactDOMServer.js",
      "npm:react@0.14.8/lib/ReactIsomorphic.js",
      "npm:react@0.14.8/lib/deprecated.js",
      "npm:react@0.14.8/lib/ReactCurrentOwner.js",
      "npm:react@0.14.8/lib/ReactVersion.js",
      "npm:fbjs@0.6.1/lib/ExecutionEnvironment.js",
      "npm:react@0.14.8/lib/ReactReconciler.js",
      "npm:react@0.14.8/lib/renderSubtreeIntoContainer.js",
      "npm:react@0.14.8/lib/ReactDOMTextComponent.js",
      "npm:react@0.14.8/lib/ReactPerf.js",
      "npm:fbjs@0.6.1/lib/warning.js",
      "npm:react@0.14.8/lib/ReactDefaultInjection.js",
      "npm:react@0.14.8/lib/ReactInstanceHandles.js",
      "npm:react@0.14.8/lib/ReactMount.js",
      "npm:react@0.14.8/lib/ReactUpdates.js",
      "npm:react@0.14.8/lib/findDOMNode.js",
      "npm:react@0.14.8/lib/ReactElement.js",
      "npm:react@0.14.8/lib/ReactServerRendering.js",
      "npm:react@0.14.8/lib/ReactChildren.js",
      "npm:react@0.14.8/lib/ReactComponent.js",
      "npm:react@0.14.8/lib/ReactClass.js",
      "npm:react@0.14.8/lib/ReactDOMFactories.js",
      "npm:react@0.14.8/lib/ReactElementValidator.js",
      "npm:react@0.14.8/lib/ReactPropTypes.js",
      "npm:react@0.14.8/lib/escapeTextContentForBrowser.js",
      "npm:fbjs@0.6.1/lib/emptyFunction.js",
      "npm:react@0.14.8/lib/ClientReactRootIndex.js",
      "npm:react@0.14.8/lib/ServerReactRootIndex.js",
      "npm:react@0.14.8/lib/ReactRootIndex.js",
      "npm:react@0.14.8/lib/ReactDOMFeatureFlags.js",
      "npm:react@0.14.8/lib/ReactEmptyComponentRegistry.js",
      "npm:react@0.14.8/lib/ReactInstanceMap.js",
      "npm:react@0.14.8/lib/shouldUpdateReactComponent.js",
      "npm:react@0.14.8/lib/ReactInjection.js",
      "npm:react@0.14.8/lib/ReactReconcileTransaction.js",
      "npm:react@0.14.8/lib/SVGDOMPropertyConfig.js",
      "npm:react@0.14.8/lib/ReactMarkupChecksum.js",
      "npm:fbjs@0.6.1/lib/containsNode.js",
      "npm:react@0.14.8/lib/ReactRef.js",
      "npm:react@0.14.8/lib/ReactComponentBrowserEnvironment.js",
      "npm:fbjs@0.6.1/lib/invariant.js",
      "npm:react@0.14.8/lib/ReactBrowserEventEmitter.js",
      "npm:fbjs@0.6.1/lib/emptyObject.js",
      "npm:react@0.14.8/lib/onlyChild.js",
      "npm:react@0.14.8/lib/DOMChildrenOperations.js",
      "npm:react@0.14.8/lib/DOMPropertyOperations.js",
      "npm:react@0.14.8/lib/setTextContent.js",
      "npm:react@0.14.8/lib/validateDOMNesting.js",
      "npm:react@0.14.8/lib/BeforeInputEventPlugin.js",
      "npm:react@0.14.8/lib/ChangeEventPlugin.js",
      "npm:react@0.14.8/lib/DefaultEventPluginOrder.js",
      "npm:react@0.14.8/lib/EnterLeaveEventPlugin.js",
      "npm:react@0.14.8/lib/HTMLDOMPropertyConfig.js",
      "npm:react@0.14.8/lib/ReactBrowserComponentMixin.js",
      "npm:react@0.14.8/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@0.14.8/lib/ReactDOMComponent.js",
      "npm:react@0.14.8/lib/ReactEventListener.js",
      "npm:react@0.14.8/lib/SelectEventPlugin.js",
      "npm:react@0.14.8/lib/SimpleEventPlugin.js",
      "npm:react@0.14.8/lib/ReactDefaultPerf.js",
      "npm:react@0.14.8/lib/DOMProperty.js",
      "npm:react@0.14.8/lib/ReactUpdateQueue.js",
      "npm:react@0.14.8/lib/instantiateReactComponent.js",
      "npm:react@0.14.8/lib/setInnerHTML.js",
      "npm:react@0.14.8/lib/CallbackQueue.js",
      "npm:react@0.14.8/lib/PooledClass.js",
      "npm:react@0.14.8/lib/Transaction.js",
      "npm:react@0.14.8/lib/ReactServerBatchingStrategy.js",
      "npm:fbjs@0.6.1/lib/keyOf.js",
      "npm:react@0.14.8/lib/getIteratorFn.js",
      "npm:fbjs@0.6.1/lib/mapObject.js",
      "npm:react@0.14.8/lib/canDefineProperty.js",
      "npm:react@0.14.8/lib/ReactPropTypeLocationNames.js",
      "npm:fbjs@0.6.1/lib/keyMirror.js",
      "npm:react@0.14.8/lib/ReactServerRenderingTransaction.js",
      "npm:react@0.14.8/lib/traverseAllChildren.js",
      "npm:react@0.14.8/lib/ReactNoopUpdateQueue.js",
      "npm:react@0.14.8/lib/ReactPropTypeLocations.js",
      "npm:react@0.14.8/lib/adler32.js",
      "npm:react@0.14.8/lib/ViewportMetrics.js",
      "npm:react@0.14.8/lib/getEventTarget.js",
      "npm:react@0.14.8/lib/isTextInputElement.js",
      "npm:react@0.14.8/lib/ReactDOMButton.js",
      "npm:fbjs@0.6.1/lib/shallowEqual.js",
      "npm:fbjs@0.6.1/lib/getUnboundedScrollPosition.js",
      "npm:fbjs@0.6.1/lib/getActiveElement.js",
      "npm:react@0.14.8/lib/getEventCharCode.js",
      "npm:react@0.14.8/lib/ReactEmptyComponent.js",
      "npm:fbjs@0.6.1/lib/isTextNode.js",
      "npm:react@0.14.8/lib/ReactEventEmitterMixin.js",
      "npm:react@0.14.8/lib/quoteAttributeValueForBrowser.js",
      "npm:react@0.14.8/lib/FallbackCompositionState.js",
      "npm:react@0.14.8/lib/SyntheticCompositionEvent.js",
      "npm:react@0.14.8/lib/SyntheticInputEvent.js",
      "npm:react@0.14.8/lib/SyntheticMouseEvent.js",
      "npm:react@0.14.8/lib/SyntheticClipboardEvent.js",
      "npm:react@0.14.8/lib/SyntheticFocusEvent.js",
      "npm:react@0.14.8/lib/SyntheticKeyboardEvent.js",
      "npm:react@0.14.8/lib/SyntheticDragEvent.js",
      "npm:react@0.14.8/lib/SyntheticTouchEvent.js",
      "npm:react@0.14.8/lib/SyntheticUIEvent.js",
      "npm:react@0.14.8/lib/SyntheticWheelEvent.js",
      "npm:react@0.14.8/lib/ReactDefaultPerfAnalysis.js",
      "npm:fbjs@0.6.1/lib/performanceNow.js",
      "npm:react@0.14.8/lib/ReactMultiChild.js",
      "npm:fbjs@0.6.1/lib/EventListener.js",
      "npm:react@0.14.8/lib/EventPluginHub.js",
      "npm:react@0.14.8/lib/ReactComponentEnvironment.js",
      "npm:react@0.14.8/lib/ReactNativeComponent.js",
      "npm:react@0.14.8/lib/ReactInputSelection.js",
      "npm:react@0.14.8/lib/ReactOwner.js",
      "npm:react@0.14.8/lib/ReactDOMIDOperations.js",
      "npm:react@0.14.8/lib/EventConstants.js",
      "npm:react@0.14.8/lib/EventPluginRegistry.js",
      "npm:react@0.14.8/lib/isEventSupported.js",
      "npm:react@0.14.8/lib/Danger.js",
      "npm:react@0.14.8/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@0.14.8/lib/EventPropagators.js",
      "npm:react@0.14.8/lib/SyntheticEvent.js",
      "npm:react@0.14.8/lib/AutoFocusUtils.js",
      "npm:react@0.14.8/lib/CSSPropertyOperations.js",
      "npm:react@0.14.8/lib/ReactDOMInput.js",
      "npm:react@0.14.8/lib/ReactDOMOption.js",
      "npm:react@0.14.8/lib/ReactDOMSelect.js",
      "npm:react@0.14.8/lib/ReactDOMTextarea.js",
      "npm:react@0.14.8/lib/ReactCompositeComponent.js",
      "npm:react@0.14.8/lib/getEventModifierState.js",
      "npm:fbjs@0.6.1/lib/isNode.js",
      "npm:react@0.14.8/lib/forEachAccumulated.js",
      "npm:fbjs@0.6.1/lib/focusNode.js",
      "npm:react@0.14.8/lib/CSSProperty.js",
      "npm:react@0.14.8/lib/getEventKey.js",
      "npm:fbjs@0.6.1/lib/performance.js",
      "npm:fbjs@0.6.1/lib/camelizeStyleName.js",
      "npm:react@0.14.8/lib/dangerousStyleValue.js",
      "npm:fbjs@0.6.1/lib/hyphenateStyleName.js",
      "npm:react@0.14.8/lib/ReactErrorUtils.js",
      "npm:fbjs@0.6.1/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.6.1/lib/getMarkupWrap.js",
      "npm:react@0.14.8/lib/getTextContentAccessor.js",
      "npm:react@0.14.8/lib/ReactChildReconciler.js",
      "npm:react@0.14.8/lib/flattenChildren.js",
      "npm:react@0.14.8/lib/EventPluginUtils.js",
      "npm:react@0.14.8/lib/accumulateInto.js",
      "npm:react@0.14.8/lib/ReactDOMSelection.js",
      "npm:fbjs@0.6.1/lib/memoizeStringOnly.js",
      "npm:react@0.14.8/lib/LinkedValueUtils.js",
      "npm:fbjs@0.6.1/lib/camelize.js",
      "npm:fbjs@0.6.1/lib/hyphenate.js",
      "npm:react@0.14.8/lib/getNodeForCharacterOffset.js",
      "npm:fbjs@0.6.1/lib/createArrayFromMixed.js",
      "npm:fbjs@0.6.1/lib/toArray.js",
      "npm:lodash@4.6.1.js",
      "npm:lodash@4.6.1/lodash.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:ieee754@1.1.6.js",
      "npm:isarray@1.0.0.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:isarray@1.0.0/index.js",
      "npm:phoenix-socket@1.1.3.js",
      "npm:phoenix-socket@1.1.3/dist/socket.js"
    ],
    "dist/dev/babel.js": [
      "npm:babel-preset-react@6.5.0.js",
      "npm:babel-preset-react@6.5.0/index.js",
      "npm:babel-plugin-transform-flow-strip-types@6.7.0.js",
      "npm:babel-plugin-transform-react-jsx@6.7.4.js",
      "npm:babel-plugin-syntax-flow@6.5.0.js",
      "npm:babel-plugin-syntax-jsx@6.5.0.js",
      "npm:babel-plugin-transform-react-display-name@6.5.0.js",
      "npm:babel-plugin-syntax-flow@6.5.0/lib/index.js",
      "npm:babel-plugin-transform-react-jsx@6.7.4/lib/index.js",
      "npm:babel-plugin-syntax-jsx@6.5.0/lib/index.js",
      "npm:babel-plugin-transform-flow-strip-types@6.7.0/lib/index.js",
      "npm:babel-plugin-transform-react-display-name@6.5.0/lib/index.js",
      "npm:babel-runtime@5.8.38/helpers/interop-require-default.js",
      "github:jspm/nodelibs-path@0.1.0.js",
      "github:jspm/nodelibs-path@0.1.0/index.js",
      "npm:path-browserify@0.0.0.js",
      "npm:path-browserify@0.0.0/index.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js",
      "npm:babel-helper-builder-react-jsx@6.6.5.js",
      "npm:babel-helper-builder-react-jsx@6.6.5/lib/index.js",
      "npm:babel-runtime@5.8.38/helpers/interop-require-wildcard.js",
      "npm:esutils@2.0.2.js",
      "npm:babel-types@6.7.2.js",
      "npm:esutils@2.0.2/lib/utils.js",
      "npm:babel-types@6.7.2/lib/index.js",
      "npm:esutils@2.0.2/lib/ast.js",
      "npm:esutils@2.0.2/lib/code.js",
      "npm:esutils@2.0.2/lib/keyword.js",
      "npm:babel-runtime@5.8.38/core-js/object/keys.js",
      "npm:babel-runtime@5.8.38/core-js/get-iterator.js",
      "npm:babel-runtime@5.8.38/helpers/defaults.js",
      "npm:babel-runtime@5.8.38/helpers/interop-export-wildcard.js",
      "npm:to-fast-properties@1.0.2.js",
      "npm:lodash@3.10.1/array/compact.js",
      "npm:lodash@3.10.1/lang/clone.js",
      "npm:lodash@3.10.1/collection/each.js",
      "npm:lodash@3.10.1/array/uniq.js",
      "npm:babel-types@6.7.2/lib/definitions/init.js",
      "npm:babel-types@6.7.2/lib/definitions/index.js",
      "npm:babel-types@6.7.2/lib/react.js",
      "npm:babel-types@6.7.2/lib/constants.js",
      "npm:babel-traverse@6.7.4.js",
      "npm:babel-types@6.7.2/lib/retrievers.js",
      "npm:babel-types@6.7.2/lib/validators.js",
      "npm:babel-types@6.7.2/lib/converters.js",
      "npm:babel-types@6.7.2/lib/flow.js",
      "npm:core-js@1.2.6/library/fn/object/keys.js",
      "npm:core-js@1.2.6/library/fn/get-iterator.js",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-names.js",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-descriptor.js",
      "npm:babel-runtime@5.8.38/core-js/object/define-property.js",
      "npm:to-fast-properties@1.0.2/index.js",
      "npm:lodash@3.10.1/internal/baseClone.js",
      "npm:lodash@3.10.1/internal/bindCallback.js",
      "npm:lodash@3.10.1/internal/isIterateeCall.js",
      "npm:lodash@3.10.1/collection/forEach.js",
      "npm:lodash@3.10.1/internal/baseCallback.js",
      "npm:lodash@3.10.1/internal/baseUniq.js",
      "npm:lodash@3.10.1/internal/sortedUniq.js",
      "npm:babel-types@6.7.2/lib/definitions/core.js",
      "npm:babel-types@6.7.2/lib/definitions/es2015.js",
      "npm:babel-types@6.7.2/lib/definitions/flow.js",
      "npm:babel-types@6.7.2/lib/definitions/jsx.js",
      "npm:babel-types@6.7.2/lib/definitions/misc.js",
      "npm:babel-types@6.7.2/lib/definitions/experimental.js",
      "npm:babel-runtime@5.8.38/core-js/symbol/for.js",
      "npm:babel-traverse@6.7.4/lib/index.js",
      "npm:babel-runtime@5.8.38/core-js/object/create.js",
      "npm:babel-runtime@5.8.38/core-js/number/max-safe-integer.js",
      "npm:lodash@3.10.1/lang/isPlainObject.js",
      "npm:lodash@3.10.1/lang/isNumber.js",
      "npm:lodash@3.10.1/lang/isRegExp.js",
      "npm:lodash@3.10.1/lang/isString.js",
      "npm:core-js@1.2.6/library/modules/es6.object.keys.js",
      "npm:core-js@1.2.6/library/modules/$.core.js",
      "npm:core-js@1.2.6/library/modules/web.dom.iterable.js",
      "npm:core-js@1.2.6/library/modules/es6.string.iterator.js",
      "npm:core-js@1.2.6/library/modules/core.get-iterator.js",
      "npm:core-js@1.2.6/library/fn/object/get-own-property-names.js",
      "npm:core-js@1.2.6/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.6/library/fn/object/define-property.js",
      "npm:lodash@3.10.1/internal/arrayCopy.js",
      "npm:lodash@3.10.1/internal/arrayEach.js",
      "npm:lodash@3.10.1/internal/baseAssign.js",
      "npm:lodash@3.10.1/internal/baseForOwn.js",
      "npm:lodash@3.10.1/internal/initCloneArray.js",
      "npm:lodash@3.10.1/internal/initCloneByTag.js",
      "npm:lodash@3.10.1/internal/initCloneObject.js",
      "npm:lodash@3.10.1/lang/isArray.js",
      "npm:lodash@3.10.1/lang/isObject.js",
      "npm:lodash@3.10.1/utility/identity.js",
      "npm:lodash@3.10.1/internal/isArrayLike.js",
      "npm:lodash@3.10.1/internal/isIndex.js",
      "npm:lodash@3.10.1/internal/baseEach.js",
      "npm:lodash@3.10.1/internal/createForEach.js",
      "npm:lodash@3.10.1/internal/baseMatches.js",
      "npm:lodash@3.10.1/internal/baseMatchesProperty.js",
      "npm:lodash@3.10.1/utility/property.js",
      "npm:lodash@3.10.1/internal/baseIndexOf.js",
      "npm:lodash@3.10.1/internal/cacheIndexOf.js",
      "npm:lodash@3.10.1/internal/createCache.js",
      "npm:core-js@1.2.6/library/fn/symbol/for.js",
      "npm:babel-runtime@5.8.38/core-js/symbol.js",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-symbols.js",
      "npm:babel-runtime@5.8.38/helpers/interop-require.js",
      "npm:babel-traverse@6.7.4/lib/context.js",
      "npm:babel-traverse@6.7.4/lib/visitors.js",
      "npm:babel-messages@6.7.2.js",
      "npm:lodash@3.10.1/collection/includes.js",
      "npm:babel-traverse@6.7.4/lib/cache.js",
      "npm:babel-traverse@6.7.4/lib/path/index.js",
      "npm:babel-traverse@6.7.4/lib/scope/index.js",
      "npm:babel-traverse@6.7.4/lib/hub.js",
      "npm:core-js@1.2.6/library/fn/object/create.js",
      "npm:core-js@1.2.6/library/fn/number/max-safe-integer.js",
      "npm:lodash@3.10.1/internal/baseForIn.js",
      "npm:lodash@3.10.1/lang/isArguments.js",
      "npm:lodash@3.10.1/internal/isObjectLike.js",
      "npm:core-js@1.2.6/library/modules/$.to-object.js",
      "npm:core-js@1.2.6/library/modules/$.object-sap.js",
      "npm:core-js@1.2.6/library/modules/es6.array.iterator.js",
      "npm:core-js@1.2.6/library/modules/$.iterators.js",
      "npm:core-js@1.2.6/library/modules/$.string-at.js",
      "npm:core-js@1.2.6/library/modules/$.iter-define.js",
      "npm:core-js@1.2.6/library/modules/$.an-object.js",
      "npm:core-js@1.2.6/library/modules/core.get-iterator-method.js",
      "npm:core-js@1.2.6/library/modules/$.js",
      "npm:core-js@1.2.6/library/modules/es6.object.get-own-property-names.js",
      "npm:core-js@1.2.6/library/modules/es6.object.get-own-property-descriptor.js",
      "npm:lodash@3.10.1/internal/baseCopy.js",
      "npm:lodash@3.10.1/object/keys.js",
      "npm:lodash@3.10.1/internal/baseFor.js",
      "npm:lodash@3.10.1/internal/bufferClone.js",
      "npm:lodash@3.10.1/internal/getNative.js",
      "npm:lodash@3.10.1/internal/isLength.js",
      "npm:lodash@3.10.1/internal/getLength.js",
      "npm:lodash@3.10.1/internal/createBaseEach.js",
      "npm:lodash@3.10.1/internal/baseIsMatch.js",
      "npm:lodash@3.10.1/internal/getMatchData.js",
      "npm:lodash@3.10.1/internal/toObject.js",
      "npm:lodash@3.10.1/internal/baseGet.js",
      "npm:lodash@3.10.1/internal/baseIsEqual.js",
      "npm:lodash@3.10.1/internal/baseSlice.js",
      "npm:lodash@3.10.1/internal/isKey.js",
      "npm:lodash@3.10.1/internal/isStrictComparable.js",
      "npm:lodash@3.10.1/array/last.js",
      "npm:lodash@3.10.1/internal/toPath.js",
      "npm:lodash@3.10.1/internal/baseProperty.js",
      "npm:lodash@3.10.1/internal/basePropertyDeep.js",
      "npm:lodash@3.10.1/internal/indexOfNaN.js",
      "npm:lodash@3.10.1/internal/SetCache.js",
      "npm:core-js@1.2.6/library/modules/es6.symbol.js",
      "npm:core-js@1.2.6/library/fn/symbol.js",
      "npm:core-js@1.2.6/library/fn/object/get-own-property-symbols.js",
      "npm:babel-runtime@5.8.38/helpers/class-call-check.js",
      "npm:babel-traverse@6.7.4/lib/path/lib/virtual-types.js",
      "npm:babel-messages@6.7.2/lib/index.js",
      "npm:lodash@3.10.1/object/values.js",
      "npm:babel-runtime@5.8.38/core-js/weak-map.js",
      "npm:debug@2.2.0.js",
      "npm:invariant@2.2.1.js",
      "npm:lodash@3.10.1/object/assign.js",
      "npm:babel-traverse@6.7.4/lib/path/ancestry.js",
      "npm:babel-traverse@6.7.4/lib/path/inference/index.js",
      "npm:babel-traverse@6.7.4/lib/path/replacement.js",
      "npm:babel-traverse@6.7.4/lib/path/evaluation.js",
      "npm:babel-traverse@6.7.4/lib/path/conversion.js",
      "npm:babel-traverse@6.7.4/lib/path/introspection.js",
      "npm:babel-traverse@6.7.4/lib/path/context.js",
      "npm:babel-traverse@6.7.4/lib/path/removal.js",
      "npm:babel-traverse@6.7.4/lib/path/modification.js",
      "npm:babel-traverse@6.7.4/lib/path/family.js",
      "npm:babel-traverse@6.7.4/lib/path/comments.js",
      "npm:babel-runtime@5.8.38/helpers/create-class.js",
      "npm:repeating@1.1.3.js",
      "npm:babel-traverse@6.7.4/lib/scope/lib/renamer.js",
      "npm:lodash@3.10.1/object/defaults.js",
      "npm:babel-traverse@6.7.4/lib/scope/binding.js",
      "npm:globals@8.18.0.js",
      "npm:core-js@1.2.6/library/modules/es6.number.max-safe-integer.js",
      "npm:lodash@3.10.1/object/keysIn.js",
      "npm:core-js@1.2.6/library/modules/$.defined.js",
      "npm:core-js@1.2.6/library/modules/$.export.js",
      "npm:core-js@1.2.6/library/modules/$.fails.js",
      "npm:core-js@1.2.6/library/modules/$.add-to-unscopables.js",
      "npm:core-js@1.2.6/library/modules/$.iter-step.js",
      "npm:core-js@1.2.6/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.6/library/modules/$.to-integer.js",
      "npm:core-js@1.2.6/library/modules/$.library.js",
      "npm:core-js@1.2.6/library/modules/$.redefine.js",
      "npm:core-js@1.2.6/library/modules/$.hide.js",
      "npm:core-js@1.2.6/library/modules/$.has.js",
      "npm:core-js@1.2.6/library/modules/$.iter-create.js",
      "npm:core-js@1.2.6/library/modules/$.set-to-string-tag.js",
      "npm:core-js@1.2.6/library/modules/$.wks.js",
      "npm:core-js@1.2.6/library/modules/$.is-object.js",
      "npm:core-js@1.2.6/library/modules/$.classof.js",
      "npm:core-js@1.2.6/library/modules/$.get-names.js",
      "npm:lodash@3.10.1/internal/shimKeys.js",
      "npm:lodash@3.10.1/internal/createBaseFor.js",
      "npm:lodash@3.10.1/lang/isNative.js",
      "npm:lodash@3.10.1/object/pairs.js",
      "npm:lodash@3.10.1/internal/baseIsEqualDeep.js",
      "npm:lodash@3.10.1/internal/baseToString.js",
      "npm:lodash@3.10.1/internal/cachePush.js",
      "npm:core-js@1.2.6/library/modules/$.global.js",
      "npm:core-js@1.2.6/library/modules/$.descriptors.js",
      "npm:core-js@1.2.6/library/modules/$.shared.js",
      "npm:core-js@1.2.6/library/modules/$.uid.js",
      "npm:core-js@1.2.6/library/modules/$.keyof.js",
      "npm:core-js@1.2.6/library/modules/$.enum-keys.js",
      "npm:core-js@1.2.6/library/modules/$.is-array.js",
      "npm:core-js@1.2.6/library/modules/$.property-desc.js",
      "npm:core-js@1.2.6/library/fn/symbol/index.js",
      "github:jspm/nodelibs-util@0.1.0.js",
      "npm:lodash@3.10.1/internal/baseValues.js",
      "npm:core-js@1.2.6/library/fn/weak-map.js",
      "npm:debug@2.2.0/browser.js",
      "npm:invariant@2.2.1/browser.js",
      "npm:lodash@3.10.1/internal/assignWith.js",
      "npm:lodash@3.10.1/internal/createAssigner.js",
      "npm:babel-traverse@6.7.4/lib/path/inference/inferers.js",
      "npm:babel-code-frame@6.7.4.js",
      "npm:babylon@6.7.0.js",
      "npm:babel-traverse@6.7.4/lib/path/lib/removal-hooks.js",
      "npm:babel-traverse@6.7.4/lib/path/lib/hoister.js",
      "npm:repeating@1.1.3/index.js",
      "npm:lodash@3.10.1/internal/assignDefaults.js",
      "npm:lodash@3.10.1/internal/createDefaults.js",
      "npm:globals@8.18.0/index.js",
      "npm:core-js@1.2.6/library/modules/$.ctx.js",
      "npm:core-js@1.2.6/library/modules/$.iobject.js",
      "npm:core-js@1.2.6/library/modules/$.cof.js",
      "npm:lodash@3.10.1/lang/isFunction.js",
      "npm:lodash@3.10.1/internal/equalArrays.js",
      "npm:lodash@3.10.1/internal/equalByTag.js",
      "npm:lodash@3.10.1/internal/equalObjects.js",
      "npm:lodash@3.10.1/lang/isTypedArray.js",
      "npm:core-js@1.2.6/library/modules/es6.object.to-string.js",
      "github:jspm/nodelibs-util@0.1.0/index.js",
      "npm:core-js@1.2.6/library/modules/es6.weak-map.js",
      "npm:debug@2.2.0/debug.js",
      "npm:lodash@3.10.1/function/restParam.js",
      "npm:babel-traverse@6.7.4/lib/path/inference/inferer-reference.js",
      "npm:babel-code-frame@6.7.4/lib/index.js",
      "npm:babylon@6.7.0/index.js",
      "npm:is-finite@1.0.1.js",
      "npm:globals@8.18.0/globals.json!github:systemjs/plugin-json@0.1.0.js",
      "npm:core-js@1.2.6/library/modules/$.a-function.js",
      "npm:lodash@3.10.1/internal/arraySome.js",
      "npm:util@0.10.3.js",
      "npm:core-js@1.2.6/library/modules/$.collection-weak.js",
      "npm:core-js@1.2.6/library/modules/$.collection.js",
      "npm:ms@0.7.1.js",
      "npm:js-tokens@1.0.3.js",
      "npm:chalk@1.1.3.js",
      "npm:is-finite@1.0.1/index.js",
      "npm:util@0.10.3/util.js",
      "npm:core-js@1.2.6/library/modules/$.redefine-all.js",
      "npm:core-js@1.2.6/library/modules/$.strict-new.js",
      "npm:core-js@1.2.6/library/modules/$.for-of.js",
      "npm:core-js@1.2.6/library/modules/$.array-methods.js",
      "npm:ms@0.7.1/index.js",
      "npm:js-tokens@1.0.3/index.js",
      "npm:chalk@1.1.3/index.js",
      "npm:number-is-nan@1.0.0.js",
      "npm:util@0.10.3/support/isBufferBrowser.js",
      "npm:inherits@2.0.1.js",
      "npm:core-js@1.2.6/library/modules/$.iter-call.js",
      "npm:core-js@1.2.6/library/modules/$.is-array-iter.js",
      "npm:core-js@1.2.6/library/modules/$.to-length.js",
      "npm:core-js@1.2.6/library/modules/$.array-species-create.js",
      "npm:escape-string-regexp@1.0.5.js",
      "npm:ansi-styles@2.2.1.js",
      "npm:strip-ansi@3.0.1.js",
      "npm:has-ansi@2.0.0.js",
      "npm:supports-color@2.0.0.js",
      "npm:number-is-nan@1.0.0/index.js",
      "npm:inherits@2.0.1/inherits_browser.js",
      "npm:escape-string-regexp@1.0.5/index.js",
      "npm:ansi-styles@2.2.1/index.js",
      "npm:strip-ansi@3.0.1/index.js",
      "npm:has-ansi@2.0.0/index.js",
      "npm:supports-color@2.0.0/index.js",
      "npm:ansi-regex@2.0.0.js",
      "npm:ansi-regex@2.0.0/index.js",
      "npm:babel-preset-es2015@6.6.0.js",
      "npm:babel-preset-es2015@6.6.0/index.js",
      "npm:babel-plugin-transform-es2015-literals@6.5.0.js",
      "npm:babel-plugin-transform-es2015-template-literals@6.6.5.js",
      "npm:babel-plugin-transform-es2015-function-name@6.5.0.js",
      "npm:babel-plugin-transform-es2015-arrow-functions@6.5.2.js",
      "npm:babel-plugin-transform-es2015-block-scoped-functions@6.6.5.js",
      "npm:babel-plugin-transform-es2015-classes@6.6.5.js",
      "npm:babel-plugin-transform-es2015-object-super@6.6.5.js",
      "npm:babel-plugin-transform-es2015-shorthand-properties@6.5.0.js",
      "npm:babel-plugin-transform-es2015-computed-properties@6.6.5.js",
      "npm:babel-plugin-transform-es2015-duplicate-keys@6.6.4.js",
      "npm:babel-plugin-transform-es2015-for-of@6.6.0.js",
      "npm:babel-plugin-transform-es2015-sticky-regex@6.5.0.js",
      "npm:babel-plugin-transform-es2015-unicode-regex@6.5.0.js",
      "npm:babel-plugin-check-es2015-constants@6.7.2.js",
      "npm:babel-plugin-transform-es2015-spread@6.6.5.js",
      "npm:babel-plugin-transform-es2015-parameters@6.7.0.js",
      "npm:babel-plugin-transform-es2015-destructuring@6.6.5.js",
      "npm:babel-plugin-transform-es2015-block-scoping@6.7.1.js",
      "npm:babel-plugin-transform-es2015-typeof-symbol@6.6.0.js",
      "npm:babel-plugin-transform-es2015-modules-commonjs@6.7.4.js",
      "npm:babel-plugin-transform-regenerator@6.6.5.js",
      "npm:babel-plugin-transform-es2015-template-literals@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-es2015-literals@6.5.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-function-name@6.5.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-arrow-functions@6.5.2/lib/index.js",
      "npm:babel-plugin-transform-es2015-for-of@6.6.0/lib/index.js",
      "npm:babel-plugin-check-es2015-constants@6.7.2/lib/index.js",
      "npm:babel-plugin-transform-es2015-spread@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-es2015-block-scoped-functions@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-es2015-classes@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-es2015-object-super@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-es2015-shorthand-properties@6.5.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-computed-properties@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-es2015-duplicate-keys@6.6.4/lib/index.js",
      "npm:babel-plugin-transform-es2015-sticky-regex@6.5.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-unicode-regex@6.5.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-parameters@6.7.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-destructuring@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-es2015-typeof-symbol@6.6.0/lib/index.js",
      "npm:babel-plugin-transform-regenerator@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-es2015-block-scoping@6.7.1/lib/index.js",
      "npm:babel-plugin-transform-es2015-modules-commonjs@6.7.4/lib/index.js",
      "npm:babel-helper-function-name@6.6.0.js",
      "npm:babel-helper-replace-supers@6.7.0.js",
      "npm:babel-helper-regex@6.6.5.js",
      "npm:regexpu-core@1.0.0.js",
      "npm:babel-plugin-transform-es2015-classes@6.6.5/lib/loose.js",
      "npm:babel-plugin-transform-es2015-classes@6.6.5/lib/vanilla.js",
      "npm:babel-plugin-transform-es2015-parameters@6.7.0/lib/default.js",
      "npm:babel-plugin-transform-es2015-parameters@6.7.0/lib/destructuring.js",
      "npm:babel-plugin-transform-es2015-parameters@6.7.0/lib/rest.js",
      "npm:lodash@3.10.1/object/extend.js",
      "npm:babel-plugin-transform-strict-mode@6.6.5.js",
      "npm:babel-template@6.7.0.js",
      "npm:babel-plugin-transform-regenerator@6.6.5/lib/visit.js",
      "npm:babel-plugin-transform-es2015-block-scoping@6.7.1/lib/tdz.js",
      "npm:babel-helper-function-name@6.6.0/lib/index.js",
      "npm:babel-runtime@5.8.38/helpers/inherits.js",
      "npm:babel-helper-optimise-call-expression@6.6.0.js",
      "npm:babel-helper-define-map@6.6.5.js",
      "npm:babel-helper-get-function-arity@6.6.5.js",
      "npm:babel-helper-call-delegate@6.6.5.js",
      "npm:babel-helper-replace-supers@6.7.0/lib/index.js",
      "npm:babel-helper-regex@6.6.5/lib/index.js",
      "npm:regexpu-core@1.0.0/rewrite-pattern.js",
      "npm:private@0.1.6.js",
      "github:jspm/nodelibs-assert@0.1.0.js",
      "npm:babel-template@6.7.0/lib/index.js",
      "npm:babel-plugin-transform-strict-mode@6.6.5/lib/index.js",
      "npm:babel-plugin-transform-regenerator@6.6.5/lib/hoist.js",
      "npm:babel-plugin-transform-regenerator@6.6.5/lib/util.js",
      "npm:babel-plugin-transform-regenerator@6.6.5/lib/emit.js",
      "npm:regjsgen@0.2.0.js",
      "npm:babel-runtime@5.8.38/core-js/object/set-prototype-of.js",
      "npm:lodash@3.10.1/array/pull.js",
      "npm:regjsparser@0.1.5.js",
      "npm:regenerate@1.2.1.js",
      "npm:regexpu-core@1.0.0/data/character-class-escape-sets.js",
      "npm:babel-helper-optimise-call-expression@6.6.0/lib/index.js",
      "npm:babel-helper-get-function-arity@6.6.5/lib/index.js",
      "npm:babel-helper-call-delegate@6.6.5/lib/index.js",
      "npm:babel-helper-define-map@6.6.5/lib/index.js",
      "npm:private@0.1.6/private.js",
      "npm:lodash@3.10.1/lang/cloneDeep.js",
      "npm:lodash@3.10.1/object/has.js",
      "github:jspm/nodelibs-assert@0.1.0/index.js",
      "npm:babel-plugin-transform-regenerator@6.6.5/lib/leap.js",
      "npm:babel-plugin-transform-regenerator@6.6.5/lib/meta.js",
      "npm:regjsgen@0.2.0/regjsgen.js",
      "npm:regjsparser@0.1.5/parser.js",
      "npm:regenerate@1.2.1/regenerate.js",
      "npm:core-js@1.2.6/library/fn/object/set-prototype-of.js",
      "npm:babel-helper-hoist-variables@6.6.5.js",
      "npm:regexpu-core@1.0.0/data/iu-mappings.json!github:systemjs/plugin-json@0.1.0.js",
      "npm:assert@1.3.0.js",
      "npm:core-js@1.2.6/library/modules/es6.object.set-prototype-of.js",
      "npm:babel-helper-hoist-variables@6.6.5/lib/index.js",
      "npm:assert@1.3.0/assert.js",
      "npm:core-js@1.2.6/library/modules/$.set-proto.js",
      "npm:babel-core@5.8.38.js",
      "npm:babel-core@5.8.38/browser.js"
    ],
    "dist/dev/app-full.js": [
      "app/js/app.js",
      "tide/logger.js",
      "app/js/polyfill.js",
      "npm:mobx@2.0.4.js",
      "npm:react-dom@0.14.8.js",
      "npm:react@0.14.8.js",
      "configuration",
      "app/js/actors/auth.js",
      "app/js/actors/rooms.js",
      "tide/views.js",
      "components/room_list.js",
      "app/js/pages/chat_lobby.js",
      "app/js/pages/chat_room.js",
      "app/js/actors/socket.js",
      "npm:mobx@2.0.4/lib/mobx.js",
      "npm:whatwg-fetch@0.11.0.js",
      "npm:react@0.14.8/react.js",
      "npm:react-dom@0.14.8/index.js",
      "app/js/models/users.js",
      "app/js/models/messages.js",
      "app/js/models/rooms.js",
      "npm:mobx-react@3.0.3.js",
      "components/chat_form.js",
      "components/user_list.js",
      "components/simple_message.js",
      "npm:lodash@4.6.1.js",
      "npm:phoenix-socket@1.1.3.js",
      "app/js/models/base.js",
      "npm:react@0.14.8/lib/ReactDOM.js",
      "npm:whatwg-fetch@0.11.0/fetch.js",
      "npm:react@0.14.8/lib/React.js",
      "npm:mobx-react@3.0.3/index.js",
      "npm:lodash@4.6.1/lodash.js",
      "npm:phoenix-socket@1.1.3/dist/socket.js",
      "npm:react@0.14.8/lib/ReactCurrentOwner.js",
      "npm:react@0.14.8/lib/ReactVersion.js",
      "npm:react@0.14.8/lib/ReactReconciler.js",
      "npm:react@0.14.8/lib/renderSubtreeIntoContainer.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "npm:react@0.14.8/lib/ReactDOMTextComponent.js",
      "npm:react@0.14.8/lib/ReactPerf.js",
      "npm:fbjs@0.6.1/lib/warning.js",
      "npm:react@0.14.8/lib/ReactInstanceHandles.js",
      "npm:react@0.14.8/lib/ReactDefaultInjection.js",
      "npm:react@0.14.8/lib/ReactMount.js",
      "npm:react@0.14.8/lib/ReactUpdates.js",
      "npm:react@0.14.8/lib/findDOMNode.js",
      "npm:fbjs@0.6.1/lib/ExecutionEnvironment.js",
      "npm:react@0.14.8/lib/ReactIsomorphic.js",
      "npm:react@0.14.8/lib/Object.assign.js",
      "npm:react@0.14.8/lib/ReactDOMServer.js",
      "npm:react@0.14.8/lib/deprecated.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "npm:react@0.14.8/lib/escapeTextContentForBrowser.js",
      "npm:react@0.14.8/lib/ReactRef.js",
      "npm:react@0.14.8/lib/ReactComponentBrowserEnvironment.js",
      "npm:react@0.14.8/lib/DOMChildrenOperations.js",
      "npm:react@0.14.8/lib/DOMPropertyOperations.js",
      "npm:react@0.14.8/lib/setTextContent.js",
      "npm:react@0.14.8/lib/validateDOMNesting.js",
      "npm:fbjs@0.6.1/lib/emptyFunction.js",
      "npm:react@0.14.8/lib/ReactRootIndex.js",
      "npm:react@0.14.8/lib/ClientReactRootIndex.js",
      "npm:react@0.14.8/lib/ServerReactRootIndex.js",
      "npm:react@0.14.8/lib/ReactDOMFeatureFlags.js",
      "npm:react@0.14.8/lib/ReactEmptyComponentRegistry.js",
      "npm:react@0.14.8/lib/ReactInstanceMap.js",
      "npm:react@0.14.8/lib/shouldUpdateReactComponent.js",
      "npm:react@0.14.8/lib/ReactInjection.js",
      "npm:react@0.14.8/lib/ReactReconcileTransaction.js",
      "npm:react@0.14.8/lib/SVGDOMPropertyConfig.js",
      "npm:react@0.14.8/lib/ReactMarkupChecksum.js",
      "npm:fbjs@0.6.1/lib/containsNode.js",
      "npm:fbjs@0.6.1/lib/invariant.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:react@0.14.8/lib/ReactBrowserEventEmitter.js",
      "npm:react@0.14.8/lib/ReactElement.js",
      "npm:fbjs@0.6.1/lib/emptyObject.js",
      "npm:react@0.14.8/lib/BeforeInputEventPlugin.js",
      "npm:react@0.14.8/lib/ChangeEventPlugin.js",
      "npm:react@0.14.8/lib/DefaultEventPluginOrder.js",
      "npm:react@0.14.8/lib/EnterLeaveEventPlugin.js",
      "npm:react@0.14.8/lib/HTMLDOMPropertyConfig.js",
      "npm:react@0.14.8/lib/ReactBrowserComponentMixin.js",
      "npm:react@0.14.8/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@0.14.8/lib/ReactDOMComponent.js",
      "npm:react@0.14.8/lib/ReactEventListener.js",
      "npm:react@0.14.8/lib/SelectEventPlugin.js",
      "npm:react@0.14.8/lib/SimpleEventPlugin.js",
      "npm:react@0.14.8/lib/ReactDefaultPerf.js",
      "npm:react@0.14.8/lib/DOMProperty.js",
      "npm:react@0.14.8/lib/ReactUpdateQueue.js",
      "npm:react@0.14.8/lib/instantiateReactComponent.js",
      "npm:react@0.14.8/lib/setInnerHTML.js",
      "npm:react@0.14.8/lib/PooledClass.js",
      "npm:react@0.14.8/lib/CallbackQueue.js",
      "npm:react@0.14.8/lib/Transaction.js",
      "npm:react@0.14.8/lib/ReactChildren.js",
      "npm:react@0.14.8/lib/ReactComponent.js",
      "npm:react@0.14.8/lib/ReactClass.js",
      "npm:react@0.14.8/lib/ReactDOMFactories.js",
      "npm:react@0.14.8/lib/ReactElementValidator.js",
      "npm:react@0.14.8/lib/ReactPropTypes.js",
      "npm:react@0.14.8/lib/onlyChild.js",
      "npm:react@0.14.8/lib/ReactServerRendering.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:react@0.14.8/lib/ReactDOMIDOperations.js",
      "npm:react@0.14.8/lib/Danger.js",
      "npm:react@0.14.8/lib/ReactOwner.js",
      "npm:react@0.14.8/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@0.14.8/lib/adler32.js",
      "npm:react@0.14.8/lib/ViewportMetrics.js",
      "npm:fbjs@0.6.1/lib/keyOf.js",
      "npm:react@0.14.8/lib/getEventTarget.js",
      "npm:react@0.14.8/lib/isTextInputElement.js",
      "npm:react@0.14.8/lib/ReactDOMButton.js",
      "npm:fbjs@0.6.1/lib/shallowEqual.js",
      "npm:fbjs@0.6.1/lib/getUnboundedScrollPosition.js",
      "npm:react@0.14.8/lib/quoteAttributeValueForBrowser.js",
      "npm:react@0.14.8/lib/ReactEmptyComponent.js",
      "npm:process@0.11.2.js",
      "npm:fbjs@0.6.1/lib/isTextNode.js",
      "npm:react@0.14.8/lib/ReactEventEmitterMixin.js",
      "npm:react@0.14.8/lib/FallbackCompositionState.js",
      "npm:react@0.14.8/lib/SyntheticCompositionEvent.js",
      "npm:react@0.14.8/lib/SyntheticInputEvent.js",
      "npm:react@0.14.8/lib/SyntheticMouseEvent.js",
      "npm:react@0.14.8/lib/canDefineProperty.js",
      "npm:react@0.14.8/lib/ReactMultiChild.js",
      "npm:fbjs@0.6.1/lib/EventListener.js",
      "npm:react@0.14.8/lib/EventPluginHub.js",
      "npm:react@0.14.8/lib/ReactComponentEnvironment.js",
      "npm:react@0.14.8/lib/ReactNativeComponent.js",
      "npm:react@0.14.8/lib/ReactInputSelection.js",
      "npm:react@0.14.8/lib/EventConstants.js",
      "npm:react@0.14.8/lib/EventPluginRegistry.js",
      "npm:react@0.14.8/lib/isEventSupported.js",
      "npm:react@0.14.8/lib/EventPropagators.js",
      "npm:react@0.14.8/lib/SyntheticEvent.js",
      "npm:react@0.14.8/lib/AutoFocusUtils.js",
      "npm:react@0.14.8/lib/CSSPropertyOperations.js",
      "npm:react@0.14.8/lib/ReactDOMInput.js",
      "npm:react@0.14.8/lib/ReactDOMOption.js",
      "npm:react@0.14.8/lib/ReactDOMSelect.js",
      "npm:react@0.14.8/lib/ReactDOMTextarea.js",
      "npm:fbjs@0.6.1/lib/getActiveElement.js",
      "npm:react@0.14.8/lib/getEventCharCode.js",
      "npm:react@0.14.8/lib/SyntheticClipboardEvent.js",
      "npm:react@0.14.8/lib/SyntheticKeyboardEvent.js",
      "npm:react@0.14.8/lib/SyntheticDragEvent.js",
      "npm:react@0.14.8/lib/SyntheticTouchEvent.js",
      "npm:react@0.14.8/lib/SyntheticFocusEvent.js",
      "npm:react@0.14.8/lib/SyntheticUIEvent.js",
      "npm:react@0.14.8/lib/SyntheticWheelEvent.js",
      "npm:react@0.14.8/lib/ReactDefaultPerfAnalysis.js",
      "npm:fbjs@0.6.1/lib/mapObject.js",
      "npm:react@0.14.8/lib/getIteratorFn.js",
      "npm:fbjs@0.6.1/lib/performanceNow.js",
      "npm:react@0.14.8/lib/ReactPropTypeLocationNames.js",
      "npm:fbjs@0.6.1/lib/keyMirror.js",
      "npm:react@0.14.8/lib/ReactNoopUpdateQueue.js",
      "npm:react@0.14.8/lib/ReactCompositeComponent.js",
      "npm:react@0.14.8/lib/traverseAllChildren.js",
      "npm:react@0.14.8/lib/ReactPropTypeLocations.js",
      "npm:react@0.14.8/lib/ReactServerBatchingStrategy.js",
      "npm:buffer@3.6.0.js",
      "npm:react@0.14.8/lib/ReactServerRenderingTransaction.js",
      "npm:fbjs@0.6.1/lib/createNodesFromMarkup.js",
      "npm:react@0.14.8/lib/getEventModifierState.js",
      "npm:fbjs@0.6.1/lib/isNode.js",
      "npm:react@0.14.8/lib/forEachAccumulated.js",
      "npm:fbjs@0.6.1/lib/focusNode.js",
      "npm:react@0.14.8/lib/CSSProperty.js",
      "npm:fbjs@0.6.1/lib/camelizeStyleName.js",
      "npm:react@0.14.8/lib/dangerousStyleValue.js",
      "npm:fbjs@0.6.1/lib/hyphenateStyleName.js",
      "npm:fbjs@0.6.1/lib/getMarkupWrap.js",
      "npm:react@0.14.8/lib/ReactErrorUtils.js",
      "npm:react@0.14.8/lib/getTextContentAccessor.js",
      "npm:react@0.14.8/lib/ReactChildReconciler.js",
      "npm:react@0.14.8/lib/flattenChildren.js",
      "npm:react@0.14.8/lib/EventPluginUtils.js",
      "npm:react@0.14.8/lib/accumulateInto.js",
      "npm:react@0.14.8/lib/ReactDOMSelection.js",
      "npm:fbjs@0.6.1/lib/memoizeStringOnly.js",
      "npm:process@0.11.2/browser.js",
      "npm:react@0.14.8/lib/getEventKey.js",
      "npm:react@0.14.8/lib/LinkedValueUtils.js",
      "npm:fbjs@0.6.1/lib/performance.js",
      "npm:buffer@3.6.0/index.js",
      "npm:fbjs@0.6.1/lib/createArrayFromMixed.js",
      "npm:fbjs@0.6.1/lib/hyphenate.js",
      "npm:fbjs@0.6.1/lib/camelize.js",
      "npm:react@0.14.8/lib/getNodeForCharacterOffset.js",
      "npm:ieee754@1.1.6.js",
      "npm:base64-js@0.0.8.js",
      "npm:isarray@1.0.0.js",
      "npm:fbjs@0.6.1/lib/toArray.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:isarray@1.0.0/index.js"
    ],
    "dist/app.js": [
      "app/js/app.js",
      "tide/logger.js",
      "configuration",
      "app/js/polyfill.js",
      "npm:mobx@2.0.4.js",
      "app/js/actors/auth.js",
      "tide/views.js",
      "components/room_list.js",
      "app/js/pages/chat_room.js",
      "app/js/pages/chat_lobby.js",
      "npm:react@0.14.8.js",
      "npm:react-dom@0.14.8.js",
      "app/js/actors/rooms.js",
      "app/js/actors/socket.js",
      "npm:mobx@2.0.4/lib/mobx.js",
      "npm:whatwg-fetch@0.11.0.js",
      "app/js/models/users.js",
      "components/chat_form.js",
      "components/user_list.js",
      "components/simple_message.js",
      "npm:mobx-react@3.0.3.js",
      "npm:lodash@4.6.1.js",
      "npm:react@0.14.8/react.js",
      "npm:react-dom@0.14.8/index.js",
      "app/js/models/messages.js",
      "app/js/models/rooms.js",
      "npm:phoenix-socket@1.1.3.js",
      "npm:whatwg-fetch@0.11.0/fetch.js",
      "app/js/models/base.js",
      "npm:react@0.14.8/lib/React.js",
      "npm:mobx-react@3.0.3/index.js",
      "npm:react@0.14.8/lib/ReactDOM.js",
      "npm:lodash@4.6.1/lodash.js",
      "npm:phoenix-socket@1.1.3/dist/socket.js",
      "npm:react@0.14.8/lib/Object.assign.js",
      "npm:react@0.14.8/lib/ReactDOMServer.js",
      "npm:react@0.14.8/lib/ReactCurrentOwner.js",
      "npm:react@0.14.8/lib/ReactVersion.js",
      "npm:fbjs@0.6.1/lib/ExecutionEnvironment.js",
      "npm:react@0.14.8/lib/ReactReconciler.js",
      "npm:react@0.14.8/lib/renderSubtreeIntoContainer.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "npm:react@0.14.8/lib/ReactIsomorphic.js",
      "npm:react@0.14.8/lib/ReactDOMTextComponent.js",
      "npm:react@0.14.8/lib/ReactPerf.js",
      "npm:fbjs@0.6.1/lib/warning.js",
      "npm:react@0.14.8/lib/deprecated.js",
      "npm:react@0.14.8/lib/ReactDefaultInjection.js",
      "npm:react@0.14.8/lib/ReactInstanceHandles.js",
      "npm:react@0.14.8/lib/ReactMount.js",
      "npm:react@0.14.8/lib/ReactUpdates.js",
      "npm:react@0.14.8/lib/findDOMNode.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "npm:react@0.14.8/lib/escapeTextContentForBrowser.js",
      "npm:fbjs@0.6.1/lib/emptyFunction.js",
      "npm:react@0.14.8/lib/ClientReactRootIndex.js",
      "npm:react@0.14.8/lib/ServerReactRootIndex.js",
      "npm:react@0.14.8/lib/ReactRootIndex.js",
      "npm:react@0.14.8/lib/ReactDOMFeatureFlags.js",
      "npm:react@0.14.8/lib/ReactEmptyComponentRegistry.js",
      "npm:react@0.14.8/lib/ReactInstanceMap.js",
      "npm:react@0.14.8/lib/shouldUpdateReactComponent.js",
      "npm:react@0.14.8/lib/ReactInjection.js",
      "npm:react@0.14.8/lib/ReactReconcileTransaction.js",
      "npm:react@0.14.8/lib/SVGDOMPropertyConfig.js",
      "npm:react@0.14.8/lib/ReactMarkupChecksum.js",
      "npm:fbjs@0.6.1/lib/containsNode.js",
      "npm:react@0.14.8/lib/ReactRef.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:react@0.14.8/lib/ReactElement.js",
      "npm:react@0.14.8/lib/ReactComponentBrowserEnvironment.js",
      "npm:fbjs@0.6.1/lib/invariant.js",
      "npm:react@0.14.8/lib/ReactBrowserEventEmitter.js",
      "npm:fbjs@0.6.1/lib/emptyObject.js",
      "npm:react@0.14.8/lib/ReactServerRendering.js",
      "npm:react@0.14.8/lib/ReactChildren.js",
      "npm:react@0.14.8/lib/ReactComponent.js",
      "npm:react@0.14.8/lib/ReactClass.js",
      "npm:react@0.14.8/lib/ReactDOMFactories.js",
      "npm:react@0.14.8/lib/ReactElementValidator.js",
      "npm:react@0.14.8/lib/ReactPropTypes.js",
      "npm:react@0.14.8/lib/onlyChild.js",
      "npm:react@0.14.8/lib/DOMChildrenOperations.js",
      "npm:react@0.14.8/lib/DOMPropertyOperations.js",
      "npm:react@0.14.8/lib/setTextContent.js",
      "npm:react@0.14.8/lib/validateDOMNesting.js",
      "npm:react@0.14.8/lib/BeforeInputEventPlugin.js",
      "npm:react@0.14.8/lib/ChangeEventPlugin.js",
      "npm:react@0.14.8/lib/DefaultEventPluginOrder.js",
      "npm:react@0.14.8/lib/EnterLeaveEventPlugin.js",
      "npm:react@0.14.8/lib/HTMLDOMPropertyConfig.js",
      "npm:react@0.14.8/lib/ReactBrowserComponentMixin.js",
      "npm:react@0.14.8/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@0.14.8/lib/ReactDOMComponent.js",
      "npm:react@0.14.8/lib/ReactEventListener.js",
      "npm:react@0.14.8/lib/SelectEventPlugin.js",
      "npm:react@0.14.8/lib/SimpleEventPlugin.js",
      "npm:react@0.14.8/lib/ReactDefaultPerf.js",
      "npm:react@0.14.8/lib/DOMProperty.js",
      "npm:react@0.14.8/lib/ReactUpdateQueue.js",
      "npm:react@0.14.8/lib/instantiateReactComponent.js",
      "npm:react@0.14.8/lib/setInnerHTML.js",
      "npm:react@0.14.8/lib/CallbackQueue.js",
      "npm:react@0.14.8/lib/PooledClass.js",
      "npm:react@0.14.8/lib/Transaction.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:react@0.14.8/lib/adler32.js",
      "npm:react@0.14.8/lib/ViewportMetrics.js",
      "npm:react@0.14.8/lib/ReactServerBatchingStrategy.js",
      "npm:fbjs@0.6.1/lib/keyOf.js",
      "npm:fbjs@0.6.1/lib/mapObject.js",
      "npm:react@0.14.8/lib/getIteratorFn.js",
      "npm:react@0.14.8/lib/getEventTarget.js",
      "npm:react@0.14.8/lib/isTextInputElement.js",
      "npm:react@0.14.8/lib/ReactDOMButton.js",
      "npm:fbjs@0.6.1/lib/shallowEqual.js",
      "npm:fbjs@0.6.1/lib/getUnboundedScrollPosition.js",
      "npm:fbjs@0.6.1/lib/getActiveElement.js",
      "npm:react@0.14.8/lib/getEventCharCode.js",
      "npm:react@0.14.8/lib/ReactEmptyComponent.js",
      "npm:fbjs@0.6.1/lib/isTextNode.js",
      "npm:process@0.11.2.js",
      "npm:react@0.14.8/lib/ReactEventEmitterMixin.js",
      "npm:react@0.14.8/lib/quoteAttributeValueForBrowser.js",
      "npm:react@0.14.8/lib/FallbackCompositionState.js",
      "npm:react@0.14.8/lib/SyntheticCompositionEvent.js",
      "npm:react@0.14.8/lib/SyntheticInputEvent.js",
      "npm:react@0.14.8/lib/SyntheticMouseEvent.js",
      "npm:react@0.14.8/lib/SyntheticClipboardEvent.js",
      "npm:react@0.14.8/lib/SyntheticFocusEvent.js",
      "npm:react@0.14.8/lib/SyntheticKeyboardEvent.js",
      "npm:react@0.14.8/lib/SyntheticDragEvent.js",
      "npm:react@0.14.8/lib/SyntheticTouchEvent.js",
      "npm:react@0.14.8/lib/SyntheticUIEvent.js",
      "npm:react@0.14.8/lib/SyntheticWheelEvent.js",
      "npm:react@0.14.8/lib/ReactDefaultPerfAnalysis.js",
      "npm:fbjs@0.6.1/lib/performanceNow.js",
      "npm:react@0.14.8/lib/canDefineProperty.js",
      "npm:react@0.14.8/lib/ReactPropTypeLocationNames.js",
      "npm:fbjs@0.6.1/lib/keyMirror.js",
      "npm:react@0.14.8/lib/ReactMultiChild.js",
      "npm:fbjs@0.6.1/lib/EventListener.js",
      "npm:react@0.14.8/lib/ReactComponentEnvironment.js",
      "npm:react@0.14.8/lib/EventPluginHub.js",
      "npm:react@0.14.8/lib/ReactNativeComponent.js",
      "npm:react@0.14.8/lib/ReactInputSelection.js",
      "npm:react@0.14.8/lib/ReactOwner.js",
      "npm:react@0.14.8/lib/ReactDOMIDOperations.js",
      "npm:react@0.14.8/lib/EventConstants.js",
      "npm:react@0.14.8/lib/EventPluginRegistry.js",
      "npm:react@0.14.8/lib/isEventSupported.js",
      "npm:react@0.14.8/lib/ReactServerRenderingTransaction.js",
      "npm:react@0.14.8/lib/traverseAllChildren.js",
      "npm:react@0.14.8/lib/ReactNoopUpdateQueue.js",
      "npm:react@0.14.8/lib/ReactPropTypeLocations.js",
      "npm:react@0.14.8/lib/Danger.js",
      "npm:react@0.14.8/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@0.14.8/lib/EventPropagators.js",
      "npm:react@0.14.8/lib/SyntheticEvent.js",
      "npm:react@0.14.8/lib/AutoFocusUtils.js",
      "npm:react@0.14.8/lib/CSSPropertyOperations.js",
      "npm:react@0.14.8/lib/ReactDOMInput.js",
      "npm:react@0.14.8/lib/ReactDOMOption.js",
      "npm:react@0.14.8/lib/ReactDOMSelect.js",
      "npm:react@0.14.8/lib/ReactDOMTextarea.js",
      "npm:react@0.14.8/lib/ReactCompositeComponent.js",
      "npm:buffer@3.6.0.js",
      "npm:fbjs@0.6.1/lib/isNode.js",
      "npm:process@0.11.2/browser.js",
      "npm:react@0.14.8/lib/getEventModifierState.js",
      "npm:react@0.14.8/lib/getEventKey.js",
      "npm:fbjs@0.6.1/lib/performance.js",
      "npm:react@0.14.8/lib/getTextContentAccessor.js",
      "npm:react@0.14.8/lib/forEachAccumulated.js",
      "npm:fbjs@0.6.1/lib/focusNode.js",
      "npm:react@0.14.8/lib/CSSProperty.js",
      "npm:fbjs@0.6.1/lib/memoizeStringOnly.js",
      "npm:fbjs@0.6.1/lib/camelizeStyleName.js",
      "npm:react@0.14.8/lib/dangerousStyleValue.js",
      "npm:fbjs@0.6.1/lib/hyphenateStyleName.js",
      "npm:react@0.14.8/lib/ReactErrorUtils.js",
      "npm:fbjs@0.6.1/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.6.1/lib/getMarkupWrap.js",
      "npm:react@0.14.8/lib/ReactChildReconciler.js",
      "npm:react@0.14.8/lib/flattenChildren.js",
      "npm:react@0.14.8/lib/EventPluginUtils.js",
      "npm:react@0.14.8/lib/accumulateInto.js",
      "npm:react@0.14.8/lib/ReactDOMSelection.js",
      "npm:react@0.14.8/lib/LinkedValueUtils.js",
      "npm:buffer@3.6.0/index.js",
      "npm:fbjs@0.6.1/lib/hyphenate.js",
      "npm:fbjs@0.6.1/lib/camelize.js",
      "npm:react@0.14.8/lib/getNodeForCharacterOffset.js",
      "npm:fbjs@0.6.1/lib/createArrayFromMixed.js",
      "npm:base64-js@0.0.8.js",
      "npm:ieee754@1.1.6.js",
      "npm:isarray@1.0.0.js",
      "npm:fbjs@0.6.1/lib/toArray.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:isarray@1.0.0/index.js"
    ]
  },
  rootURL: "/",

  packages: {
    "chat": {
      "defaultExtension": "js"
    }
  },
  todo_normalize: "https://github.com/jspm/jspm-cli/issues/621#issuecomment-99083976",

  map: {
    "babel": "npm:babel-core@5.8.38",
    "babel-preset-es2015": "npm:babel-preset-es2015@6.6.0",
    "babel-preset-react": "npm:babel-preset-react@6.5.0",
    "babel-preset-stage-0": "npm:babel-preset-stage-0@6.5.0",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "core-js": "npm:core-js@1.2.6",
    "es6-enum": "npm:es6-enum@1.0.3",
    "lodash": "npm:lodash@4.6.1",
    "mobx": "npm:mobx@2.0.4",
    "mobx-react": "npm:mobx-react@3.0.3",
    "phoenix-socket": "npm:phoenix-socket@1.1.3",
    "react": "npm:react@0.14.8",
    "react-dom": "npm:react-dom@0.14.8",
    "whatwg-fetch": "npm:whatwg-fetch@0.11.0",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-net@0.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "timers": "github:jspm/nodelibs-timers@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-querystring@0.1.0": {
      "querystring": "npm:querystring@0.2.0"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-timers@0.1.0": {
      "timers-browserify": "npm:timers-browserify@1.4.2"
    },
    "github:jspm/nodelibs-tty@0.1.0": {
      "tty-browserify": "npm:tty-browserify@0.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:amdefine@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:asn1.js@4.5.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.11.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-code-frame@6.7.4": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "chalk": "npm:chalk@1.1.3",
      "esutils": "npm:esutils@2.0.2",
      "js-tokens": "npm:js-tokens@1.0.3",
      "repeating": "npm:repeating@1.1.3"
    },
    "npm:babel-core@6.7.4": {
      "babel-code-frame": "npm:babel-code-frame@6.7.4",
      "babel-generator": "npm:babel-generator@6.7.2",
      "babel-helpers": "npm:babel-helpers@6.6.0",
      "babel-messages": "npm:babel-messages@6.7.2",
      "babel-register": "npm:babel-register@6.7.2",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2",
      "babylon": "npm:babylon@6.7.0",
      "convert-source-map": "npm:convert-source-map@1.2.0",
      "debug": "npm:debug@2.2.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "json5": "npm:json5@0.4.0",
      "lodash": "npm:lodash@3.10.1",
      "minimatch": "npm:minimatch@2.0.10",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "path-exists": "npm:path-exists@1.0.0",
      "path-is-absolute": "npm:path-is-absolute@1.0.0",
      "private": "npm:private@0.1.6",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "shebang-regex": "npm:shebang-regex@1.0.0",
      "slash": "npm:slash@1.0.0",
      "source-map": "npm:source-map@0.5.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:babel-generator@6.7.2": {
      "babel-messages": "npm:babel-messages@6.7.2",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "detect-indent": "npm:detect-indent@3.0.1",
      "is-integer": "npm:is-integer@1.0.6",
      "lodash": "npm:lodash@3.10.1",
      "repeating": "npm:repeating@1.1.3",
      "source-map": "npm:source-map@0.5.3",
      "trim-right": "npm:trim-right@1.0.1"
    },
    "npm:babel-helper-bindify-decorators@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-builder-binary-assignment-operator-visitor@6.6.5": {
      "babel-helper-explode-assignable-expression": "npm:babel-helper-explode-assignable-expression@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-builder-react-jsx@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2",
      "esutils": "npm:esutils@2.0.2",
      "lodash": "npm:lodash@3.10.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:babel-helper-call-delegate@6.6.5": {
      "babel-helper-hoist-variables": "npm:babel-helper-hoist-variables@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-define-map@6.6.5": {
      "babel-helper-function-name": "npm:babel-helper-function-name@6.6.0",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2",
      "lodash": "npm:lodash@3.10.1"
    },
    "npm:babel-helper-explode-assignable-expression@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-explode-class@6.6.5": {
      "babel-helper-bindify-decorators": "npm:babel-helper-bindify-decorators@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-function-name@6.6.0": {
      "babel-helper-get-function-arity": "npm:babel-helper-get-function-arity@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-get-function-arity@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-hoist-variables@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-optimise-call-expression@6.6.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-regex@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2",
      "lodash": "npm:lodash@3.10.1"
    },
    "npm:babel-helper-remap-async-to-generator@6.7.0": {
      "babel-helper-function-name": "npm:babel-helper-function-name@6.6.0",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helper-replace-supers@6.7.0": {
      "babel-helper-optimise-call-expression": "npm:babel-helper-optimise-call-expression@6.6.0",
      "babel-messages": "npm:babel-messages@6.7.2",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-helpers@6.6.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0"
    },
    "npm:babel-messages@6.7.2": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:babel-plugin-check-es2015-constants@6.7.2": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-async-functions@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-class-constructor-call@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-class-properties@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-decorators@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-do-expressions@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-exponentiation-operator@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-export-extensions@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-flow@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-function-bind@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-jsx@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-object-rest-spread@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-syntax-trailing-function-commas@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-async-to-generator@6.7.4": {
      "babel-helper-remap-async-to-generator": "npm:babel-helper-remap-async-to-generator@6.7.0",
      "babel-plugin-syntax-async-functions": "npm:babel-plugin-syntax-async-functions@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-class-constructor-call@6.6.5": {
      "babel-plugin-syntax-class-constructor-call": "npm:babel-plugin-syntax-class-constructor-call@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0"
    },
    "npm:babel-plugin-transform-class-properties@6.6.0": {
      "babel-plugin-syntax-class-properties": "npm:babel-plugin-syntax-class-properties@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-decorators@6.6.5": {
      "babel-helper-define-map": "npm:babel-helper-define-map@6.6.5",
      "babel-helper-explode-class": "npm:babel-helper-explode-class@6.6.5",
      "babel-plugin-syntax-decorators": "npm:babel-plugin-syntax-decorators@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-plugin-transform-do-expressions@6.5.0": {
      "babel-plugin-syntax-do-expressions": "npm:babel-plugin-syntax-do-expressions@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-arrow-functions@6.5.2": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-block-scoped-functions@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-block-scoping@6.7.1": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2",
      "lodash": "npm:lodash@3.10.1"
    },
    "npm:babel-plugin-transform-es2015-classes@6.6.5": {
      "babel-helper-define-map": "npm:babel-helper-define-map@6.6.5",
      "babel-helper-function-name": "npm:babel-helper-function-name@6.6.0",
      "babel-helper-optimise-call-expression": "npm:babel-helper-optimise-call-expression@6.6.0",
      "babel-helper-replace-supers": "npm:babel-helper-replace-supers@6.7.0",
      "babel-messages": "npm:babel-messages@6.7.2",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-plugin-transform-es2015-computed-properties@6.6.5": {
      "babel-helper-define-map": "npm:babel-helper-define-map@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0"
    },
    "npm:babel-plugin-transform-es2015-destructuring@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-duplicate-keys@6.6.4": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-plugin-transform-es2015-for-of@6.6.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-function-name@6.5.0": {
      "babel-helper-function-name": "npm:babel-helper-function-name@6.6.0",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-plugin-transform-es2015-literals@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-modules-commonjs@6.7.4": {
      "babel-plugin-transform-strict-mode": "npm:babel-plugin-transform-strict-mode@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-types": "npm:babel-types@6.7.2",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:babel-plugin-transform-es2015-object-super@6.6.5": {
      "babel-helper-replace-supers": "npm:babel-helper-replace-supers@6.7.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-parameters@6.7.0": {
      "babel-helper-call-delegate": "npm:babel-helper-call-delegate@6.6.5",
      "babel-helper-get-function-arity": "npm:babel-helper-get-function-arity@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-template": "npm:babel-template@6.7.0",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-plugin-transform-es2015-shorthand-properties@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-plugin-transform-es2015-spread@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-sticky-regex@6.5.0": {
      "babel-helper-regex": "npm:babel-helper-regex@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-plugin-transform-es2015-template-literals@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-typeof-symbol@6.6.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-es2015-unicode-regex@6.5.0": {
      "babel-helper-regex": "npm:babel-helper-regex@6.6.5",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "regexpu-core": "npm:regexpu-core@1.0.0"
    },
    "npm:babel-plugin-transform-exponentiation-operator@6.5.0": {
      "babel-helper-builder-binary-assignment-operator-visitor": "npm:babel-helper-builder-binary-assignment-operator-visitor@6.6.5",
      "babel-plugin-syntax-exponentiation-operator": "npm:babel-plugin-syntax-exponentiation-operator@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-export-extensions@6.5.0": {
      "babel-plugin-syntax-export-extensions": "npm:babel-plugin-syntax-export-extensions@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-flow-strip-types@6.7.0": {
      "babel-plugin-syntax-flow": "npm:babel-plugin-syntax-flow@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-function-bind@6.5.2": {
      "babel-plugin-syntax-function-bind": "npm:babel-plugin-syntax-function-bind@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-object-rest-spread@6.6.5": {
      "babel-plugin-syntax-object-rest-spread": "npm:babel-plugin-syntax-object-rest-spread@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-react-display-name@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:babel-plugin-transform-react-jsx-source@6.5.0": {
      "babel-plugin-syntax-jsx": "npm:babel-plugin-syntax-jsx@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-react-jsx@6.7.4": {
      "babel-helper-builder-react-jsx": "npm:babel-helper-builder-react-jsx@6.6.5",
      "babel-plugin-syntax-jsx": "npm:babel-plugin-syntax-jsx@6.5.0",
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-plugin-transform-regenerator@6.6.5": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "babel-core": "npm:babel-core@6.7.4",
      "babel-plugin-syntax-async-functions": "npm:babel-plugin-syntax-async-functions@6.5.0",
      "babel-plugin-transform-es2015-block-scoping": "npm:babel-plugin-transform-es2015-block-scoping@6.7.1",
      "babel-plugin-transform-es2015-for-of": "npm:babel-plugin-transform-es2015-for-of@6.6.0",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2",
      "babylon": "npm:babylon@6.7.0",
      "private": "npm:private@0.1.6",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:babel-plugin-transform-strict-mode@6.6.5": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2"
    },
    "npm:babel-preset-es2015@6.6.0": {
      "babel-plugin-check-es2015-constants": "npm:babel-plugin-check-es2015-constants@6.7.2",
      "babel-plugin-transform-es2015-arrow-functions": "npm:babel-plugin-transform-es2015-arrow-functions@6.5.2",
      "babel-plugin-transform-es2015-block-scoped-functions": "npm:babel-plugin-transform-es2015-block-scoped-functions@6.6.5",
      "babel-plugin-transform-es2015-block-scoping": "npm:babel-plugin-transform-es2015-block-scoping@6.7.1",
      "babel-plugin-transform-es2015-classes": "npm:babel-plugin-transform-es2015-classes@6.6.5",
      "babel-plugin-transform-es2015-computed-properties": "npm:babel-plugin-transform-es2015-computed-properties@6.6.5",
      "babel-plugin-transform-es2015-destructuring": "npm:babel-plugin-transform-es2015-destructuring@6.6.5",
      "babel-plugin-transform-es2015-duplicate-keys": "npm:babel-plugin-transform-es2015-duplicate-keys@6.6.4",
      "babel-plugin-transform-es2015-for-of": "npm:babel-plugin-transform-es2015-for-of@6.6.0",
      "babel-plugin-transform-es2015-function-name": "npm:babel-plugin-transform-es2015-function-name@6.5.0",
      "babel-plugin-transform-es2015-literals": "npm:babel-plugin-transform-es2015-literals@6.5.0",
      "babel-plugin-transform-es2015-modules-commonjs": "npm:babel-plugin-transform-es2015-modules-commonjs@6.7.4",
      "babel-plugin-transform-es2015-object-super": "npm:babel-plugin-transform-es2015-object-super@6.6.5",
      "babel-plugin-transform-es2015-parameters": "npm:babel-plugin-transform-es2015-parameters@6.7.0",
      "babel-plugin-transform-es2015-shorthand-properties": "npm:babel-plugin-transform-es2015-shorthand-properties@6.5.0",
      "babel-plugin-transform-es2015-spread": "npm:babel-plugin-transform-es2015-spread@6.6.5",
      "babel-plugin-transform-es2015-sticky-regex": "npm:babel-plugin-transform-es2015-sticky-regex@6.5.0",
      "babel-plugin-transform-es2015-template-literals": "npm:babel-plugin-transform-es2015-template-literals@6.6.5",
      "babel-plugin-transform-es2015-typeof-symbol": "npm:babel-plugin-transform-es2015-typeof-symbol@6.6.0",
      "babel-plugin-transform-es2015-unicode-regex": "npm:babel-plugin-transform-es2015-unicode-regex@6.5.0",
      "babel-plugin-transform-regenerator": "npm:babel-plugin-transform-regenerator@6.6.5"
    },
    "npm:babel-preset-react@6.5.0": {
      "babel-plugin-syntax-flow": "npm:babel-plugin-syntax-flow@6.5.0",
      "babel-plugin-syntax-jsx": "npm:babel-plugin-syntax-jsx@6.5.0",
      "babel-plugin-transform-flow-strip-types": "npm:babel-plugin-transform-flow-strip-types@6.7.0",
      "babel-plugin-transform-react-display-name": "npm:babel-plugin-transform-react-display-name@6.5.0",
      "babel-plugin-transform-react-jsx": "npm:babel-plugin-transform-react-jsx@6.7.4",
      "babel-plugin-transform-react-jsx-source": "npm:babel-plugin-transform-react-jsx-source@6.5.0"
    },
    "npm:babel-preset-stage-0@6.5.0": {
      "babel-plugin-transform-do-expressions": "npm:babel-plugin-transform-do-expressions@6.5.0",
      "babel-plugin-transform-function-bind": "npm:babel-plugin-transform-function-bind@6.5.2",
      "babel-preset-stage-1": "npm:babel-preset-stage-1@6.5.0"
    },
    "npm:babel-preset-stage-1@6.5.0": {
      "babel-plugin-transform-class-constructor-call": "npm:babel-plugin-transform-class-constructor-call@6.6.5",
      "babel-plugin-transform-class-properties": "npm:babel-plugin-transform-class-properties@6.6.0",
      "babel-plugin-transform-decorators": "npm:babel-plugin-transform-decorators@6.6.5",
      "babel-plugin-transform-export-extensions": "npm:babel-plugin-transform-export-extensions@6.5.0",
      "babel-preset-stage-2": "npm:babel-preset-stage-2@6.5.0"
    },
    "npm:babel-preset-stage-2@6.5.0": {
      "babel-plugin-syntax-trailing-function-commas": "npm:babel-plugin-syntax-trailing-function-commas@6.5.0",
      "babel-plugin-transform-object-rest-spread": "npm:babel-plugin-transform-object-rest-spread@6.6.5",
      "babel-preset-stage-3": "npm:babel-preset-stage-3@6.5.0"
    },
    "npm:babel-preset-stage-3@6.5.0": {
      "babel-plugin-transform-async-to-generator": "npm:babel-plugin-transform-async-to-generator@6.7.4",
      "babel-plugin-transform-exponentiation-operator": "npm:babel-plugin-transform-exponentiation-operator@6.5.0"
    },
    "npm:babel-register@6.7.2": {
      "babel-core": "npm:babel-core@6.7.4",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "core-js": "npm:core-js@2.2.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "home-or-tmp": "npm:home-or-tmp@1.0.0",
      "lodash": "npm:lodash@3.10.1",
      "mkdirp": "npm:mkdirp@0.5.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "path-exists": "npm:path-exists@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map-support": "npm:source-map-support@0.2.10"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:babel-template@6.7.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "babel-types": "npm:babel-types@6.7.2",
      "babylon": "npm:babylon@6.7.0",
      "lodash": "npm:lodash@3.10.1"
    },
    "npm:babel-traverse@6.7.4": {
      "babel-code-frame": "npm:babel-code-frame@6.7.4",
      "babel-messages": "npm:babel-messages@6.7.2",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-types": "npm:babel-types@6.7.2",
      "babylon": "npm:babylon@6.7.0",
      "debug": "npm:debug@2.2.0",
      "globals": "npm:globals@8.18.0",
      "invariant": "npm:invariant@2.2.1",
      "lodash": "npm:lodash@3.10.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "repeating": "npm:repeating@1.1.3"
    },
    "npm:babel-types@6.7.2": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "babel-traverse": "npm:babel-traverse@6.7.4",
      "esutils": "npm:esutils@2.0.2",
      "lodash": "npm:lodash@3.10.1",
      "to-fast-properties": "npm:to-fast-properties@1.0.2"
    },
    "npm:babylon@6.7.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:balanced-match@0.3.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:bn.js@4.11.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:brace-expansion@1.1.3": {
      "balanced-match": "npm:balanced-match@0.3.0",
      "concat-map": "npm:concat-map@0.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.11.1",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:chalk@1.1.3": {
      "ansi-styles": "npm:ansi-styles@2.2.1",
      "escape-string-regexp": "npm:escape-string-regexp@1.0.5",
      "has-ansi": "npm:has-ansi@2.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "strip-ansi": "npm:strip-ansi@3.0.1",
      "supports-color": "npm:supports-color@2.0.0"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:convert-source-map@1.2.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@2.2.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.5"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:d@0.1.1": {
      "es5-ext": "npm:es5-ext@0.10.11"
    },
    "npm:debug@2.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ms": "npm:ms@0.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tty": "github:jspm/nodelibs-tty@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:detect-indent@3.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "get-stdin": "npm:get-stdin@4.0.1",
      "minimist": "npm:minimist@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "repeating": "npm:repeating@1.1.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@6.2.3": {
      "bn.js": "npm:bn.js@4.11.1",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:es5-ext@0.10.11": {
      "es6-iterator": "npm:es6-iterator@2.0.0",
      "es6-symbol": "npm:es6-symbol@3.0.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:es6-enum@1.0.3": {
      "es6-symbol": "npm:es6-symbol@3.0.2"
    },
    "npm:es6-iterator@2.0.0": {
      "d": "npm:d@0.1.1",
      "es5-ext": "npm:es5-ext@0.10.11",
      "es6-symbol": "npm:es6-symbol@3.0.2"
    },
    "npm:es6-symbol@3.0.2": {
      "d": "npm:d@0.1.1",
      "es5-ext": "npm:es5-ext@0.10.11"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:fbjs@0.6.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:get-stdin@4.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:globals@8.18.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:has-ansi@2.0.0": {
      "ansi-regex": "npm:ansi-regex@2.0.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:home-or-tmp@1.0.0": {
      "os-tmpdir": "npm:os-tmpdir@1.0.1",
      "user-home": "npm:user-home@1.1.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:invariant@2.2.1": {
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:is-finite@1.0.1": {
      "number-is-nan": "npm:number-is-nan@1.0.0"
    },
    "npm:is-integer@1.0.6": {
      "is-finite": "npm:is-finite@1.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:isarray@1.0.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:json5@0.4.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:lodash@3.10.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:lodash@4.6.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:loose-envify@1.1.0": {
      "js-tokens": "npm:js-tokens@1.0.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.11.1",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:minimatch@2.0.10": {
      "brace-expansion": "npm:brace-expansion@1.1.3",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:mkdirp@0.5.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "minimist": "npm:minimist@0.0.8",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:mobx-react@3.0.3": {
      "mobx": "npm:mobx@2.0.4"
    },
    "npm:os-tmpdir@1.0.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.5.2",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-exists@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:path-is-absolute@1.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:phoenix-socket@1.1.3": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.1",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:randombytes@2.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:react-dom@0.14.8": {
      "react": "npm:react@0.14.8"
    },
    "npm:react@0.14.8": {
      "fbjs": "npm:fbjs@0.6.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:regenerate@1.2.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:regexpu-core@1.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "regenerate": "npm:regenerate@1.2.1",
      "regjsgen": "npm:regjsgen@0.2.0",
      "regjsparser": "npm:regjsparser@0.1.5",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:regjsparser@0.1.5": {
      "jsesc": "npm:jsesc@0.5.0"
    },
    "npm:repeating@1.1.3": {
      "is-finite": "npm:is-finite@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:source-map-support@0.2.10": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "querystring": "github:jspm/nodelibs-querystring@0.1.0",
      "source-map": "npm:source-map@0.1.32"
    },
    "npm:source-map@0.1.32": {
      "amdefine": "npm:amdefine@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:source-map@0.5.3": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:strip-ansi@3.0.1": {
      "ansi-regex": "npm:ansi-regex@2.0.0"
    },
    "npm:supports-color@2.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:timers-browserify@1.4.2": {
      "process": "npm:process@0.11.2"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:user-home@1.1.1": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  }
});
